name: "bug提交"
description: "bug提交"
labels: [BUG, 新提交]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    - label: "我已在 [Issues 页面](https://github.com/wengjinju/universal-wall/issues) 中搜索，确认了这一 Bug 未被提交过。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "详细描述具体表现。"
  validations:
    required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 预期行为
    description: "对您期望发生的事情的清晰简洁描述。"
  validations:
    required: false
- type: textarea
  id: "yml-2"
  attributes:
    label: 环境
    description: "操作系统、浏览器、版本"
  validations:
    required: false
- type: textarea
  id: "yml-2"
  attributes:
    label: 备注
    description: "在此处添加有关问题的其他背景信息。
  validations:
    required: false
- type: textarea
  id: "yml-3"
  attributes:
    label: 截图
    description: "请添加截图以帮助解释您的问题。"
    placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
  validations:
    required: false
